"""加入post.body_html

Revision ID: 610387e7bf52
Revises: d3f081daf3d7
Create Date: 2019-07-21 14:20:21.896656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610387e7bf52'
down_revision = 'd3f081daf3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
